# refer https://github.com/tursodatabase/libsql/blob/main/docs/DOCKER.md#docker-compose
services:
  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "5001:5001"
    # environment:
      # - SQLD_NODE=primary # Possible values are: primary (default), replica, and standalone
    volumes:
      - ./data/libsql:/var/lib/sqld
